### ISSUE TITLE
Двойные кавычки в gulpfile

### ISSUE THREAD

**Issue by pinkypupa** [htmlacademy/html2-basic-template#42]
Добрый день :) 
Я студентка, которая скачала template и немножко провозилась с тем, что при npm run у меня sass не хотел собираться. 
Предлагаю исправить двойные кавычки на одинарные в импортах в gulpfile.js, чтобы будущие студенты, которые будут скачивать шаблон сборки, страдали чуть меньше :)

**Comment by nikolai-shabalin** [comment]
Поправил. Спасибо за помощь
