### ISSUE TITLE
Сменить основную ветку

### ISSUE THREAD

**Issue by firefoxic** [htmlacademy/html2-basic-template#47]
У студентов всё ещё `master`, и скорее всего будет на ближайшем потоке тоже.
А в этом репозитории `main`. В этом несоответствии есть проблемы:
- GitHub-экшены не настроить так, чтобы и тут работало и у студентов.
- На курсе привыкают к `master`, и уже сразу на грейдировании получают `main`, а в реальных проектах уже почти не встретить `master`.
	
По хорошему бы надо и на курсе `main` сделать. Вопрос лишь в том, успеет ли команда разработки до ближайшего потока сделать 2 вещи:
- [ ] Изменить основную ветку в автоматически создаваемых репозиториях студентов.
- [ ] Изменить имя ветки во всех сценариях и экшенах (деплой по клику в интерфейсе курса, возможно что-то в автотестах).
	
Если не успеет и/или не захочет — то надо изменить в этом репозитории. Это быстрее и проще, но всё равно не на пользу студентам.

**Comment by nikolai-shabalin** [comment]
Внутри компании куча работы по поводу смены `master` на `main` на которую нужно куча ресурсов. Пока компания не готова столько тратить на ренейминг. Я об этом уже год назад спрашивал. С места ничего не сдвинулось. Поэтому поменяю здесь

**Comment by firefoxic** [comment]
Похоже нужна ишья в ё-моё, иначе никогда не сдвинется…

**Comment by nikolai-shabalin** [comment]
> Похоже нужна ишья в ё-моё, иначе никогда не сдвинется…

У ребят слишком серьёзные планы на ренейминг, там не будет частичного для HTML1, а потом для HTML2, а потом там-то. Хотят сразу. Потому что слишком много автоматики, в виде деплоев, настроено на `master`

**Comment by firefoxic** [comment]
А это просто чтобы ссылка у акселерашек не сломалась?
![image](https://github.com/htmlacademy/html2-basic-template/assets/3382798/788ef115-4cf9-4be2-8945-d6e0450c31da)

**Comment by nikolai-shabalin** [comment]
> А это просто чтобы ссылка у акселерашек не сломалась? ![image](https://user-images.githubusercontent.com/3382798/281397749-788ef115-4cf9-4be2-8945-d6e0450c31da.png)

Да, всё верно. Пока решил не удалять, чтобы не нервировать особенно тревожных
