### ISSUE TITLE
Улучшения сборки

### ISSUE THREAD

**Issue by firefoxic** [htmlacademy/html2-basic-template#50]
Вот теперь, когда причесал проект, таки взялся за большое улучшение сборки, а именно dev-режим.
Для этого ещё некоторые приготовления делаю в галпфайле.

Но вот некоторые моменты хотелось бы прояснить.

### 1. Нам всё ещё нужно иметь папку `icons/` внутри `images/`?

Раньше, когда студенты сами сборку писали (некоторые 👀) это было чем-то вроде образовательного момента — научить делать исключения выборки паттернов. Но сейчас этот поинт неактуальный. Есть ли ещё какие-то причины такого расположения?

Сборка с раздельными `icons/` и `images/` была бы чуть попроще.

---

_Далее ещё возможно буду докидывать вопросы в эту ишью._

**Comment by firefoxic** [comment]
### 2. Шаблонизатор

Кажется уже можно добавлять его в сборку. Пока опционально. То есть он будет работать под капотом, но можно продолжать писать обычную портянку html. А кто чувствует в себе силы, может начинать потихоньку. То есть это такой progressive enhancement.

Вот только я бы всё-таки лучше nunjucks рекомендовал. Твиг не лучший выбор для курса по нескольким причинам:
- Документация твига отвратительнейшая, особенно новичкам. У nunjucks значительно понятнее.
- Макросы в nunjucks адекватнее.
- Обычно используемый плагин для него — кривой, надо вместо gulp-twig использовать связку twing + gulp-twing, которые больше соответствуют пыховому твигу.
- Если переезжать с gulp на vite, у меня нет гарантий, что плагины твига под vite верно работают, а nunjucks всегда один и тот же.

**Comment by firefoxic** [comment]
@nikolai-shabalin я кажется немного упёрся в развилку на пункте №1 🤔
Можем мы вытащить icons из images?

**Comment by nikolai-shabalin** [comment]
## 1. Нам всё ещё нужно иметь папку icons/ внутри images/?
Кажется, что абсолютно все кладут иконки в `images`. Тут у вышедшего студента с курсов может случится диссонанс. На курсе так, а в жизни по другому.

Лучше это момент сначала исследовать хорошенько и только после этого внедрять в курс. Походить по чужим сборкам. Поспрашивать в учительской. Пока не стоит ничего для иконок менять.


## 2. Шаблонизатор
Если это будет HTML-first, то я не против. Главное, чтобы студент не отвлекался на "О! А чё это такое. А дайте-ка изучу и завалю курс" =)

Ещё вопрос. Нунчаки могут просто с HTML-работать? Беру HTML откуда-то копирую в нунчаки и всё работает. В общем, как в SCSS

**Comment by firefoxic** [comment]
> Если это будет HTML-first, то я не против.

Это же нунчаки 🥰

> Нунчаки могут просто с HTML-работать? Беру HTML откуда-то копирую в нунчаки и всё работает.

Они почти 100% совместимы с twig. В том числе и в том, как работают с чистым html — просто отдают его как есть.

**Comment by firefoxic** [comment]
Кстати, на счёт ассетсов. Можно и собрать их все в одну папку. Может студенам даже удобнее будет что-то вроде такого:

```shell
├── source/
    └── assets/
        ├── favicons/
        ├── fonts/
        ├── icons/
        └── images/
```

**Comment by firefoxic** [comment]
Правда и в сырьё тогда придётся это дело для картинок+иконок зеркалить:

```shell
├── raw/
    └── assets/
        ├── icons/
        └── images/
```
🤔

**Comment by firefoxic** [comment]
### 3. Шрифты

Совсем забыли, что `woff` упразднили. Можно в таске оставить его на всякий случай. Но в ридмишках наверное лучше лишнюю инфу поудалять, чтобы чуточку разгрузить и без того большую телегу информации о сборке.

**Comment by nikolai-shabalin** [comment]
> ### 3. Шрифты
> Совсем забыли, что `woff` упразднили. Можно в таске оставить его на всякий случай. Но в ридмишках наверное лучше лишнюю инфу поудалять, чтобы чуточку разгрузить и без того большую телегу информации о сборке.

Да, в таске оставим потому что ничего плохого в добавлении woff нет, а вот из описаний можно удалить упоминание, чтобы не мозолило глаза

**Comment by firefoxic** [comment]
Чуть не забыл… Есть ещё одна причина, по которой лучше бы вынести `icons/` из `images/`. Не хотел говорить об этом раньше коммита, но ладно уж))
В общем я хочу сделать для дев-сервера роутинг статики (ассетсов? ну в общем всей этой приблуды 🤭) в сорцы, не копируя её в `build/`. И вот тут желательно бы развести совсем статичные картинки (просто копируемые в билд при прод-сборке, а в дев — сервер будет просто ходить за ними в source) и иконки, которые в спрайт надо собрать и положить в билд (даже в дев режиме).

**Comment by nikolai-shabalin** [comment]
Предлагаю инфу про ассеты и разделение `icons` с `images` вынести в отдельную таску.
В этой же задаче постараться собрать статистику из разных популярных библиотек. Мне сейчас не кажется, что это нужное обновление. Я бы на него уже через поток смотрел пристальнее

**Comment by firefoxic** [comment]
> из описаний можно удалить
Коммит уже в PR 👀
