### ISSUE TITLE
Переименовать `global/` в `common/`

### ISSUE THREAD

**Issue by firefoxic** [htmlacademy/html2-basic-template#73]
Очень сложно объяснять студентам, что куда класть, когда оно названо нелогично. И приходится выкручиваться, предлагая представить, что папка называется `common/` — тогда и нет этого `global/global.scss`, и легко объясняется всё:
![image](https://github.com/htmlacademy/html2-basic-template/assets/3382798/ea1d3820-7997-4569-b07d-28438c58f801)

**Comment by nikolai-shabalin** [comment]
Да, давай

**Comment by firefoxic** [comment]
Вообще я в проектах чаще встречал `shared`, но показалось что студенту проще слово `common` понять.
