### ISSUE TITLE
Переписать gulp-таски со стрелочных функций на обычные

### ISSUE THREAD

**Issue by firefoxic** [htmlacademy/html2-basic-template#9]
Готов запулреквестить этот [пропосал](https://github.com/htmlacademy/yomoyo/issues/1067).

Но наверное уже после принятия предыдущих пулреквестов, а то совсем запарюсь ребейзить и конфлиты разруливать.

**Comment by nikolai-shabalin** [comment]
Сможешь в этом же PR сделать названия функций глаголами + перевести на `function()`? Подсмотрел у тебя в проектах и надо бы у нас поправить

**Comment by firefoxic** [comment]
Смогу)

**Comment by nikolai-shabalin** [comment]
Буду очень благодарен
